#pragma once

#include <openmedia/byte.h>
#include <openmedia/media.h>

#if defined(__cplusplus)
extern "C" {
#endif

OM_ENUM(OMCodecId, uint32_t) {
  OM_CODEC_NONE = 0,

  // Video codecs
  OM_CODEC_H261 = OM_MAGIC('H261'),
  OM_CODEC_H262 = OM_MAGIC('H262'),
  OM_CODEC_MPEG2 = OM_CODEC_H262,
  OM_CODEC_H263 = OM_MAGIC('H263'),
  OM_CODEC_H264 = OM_MAGIC('AVC1'),
  OM_CODEC_AVC = OM_CODEC_H264,
  OM_CODEC_H265 = OM_MAGIC('HVC1'),
  OM_CODEC_HEVC = OM_CODEC_H265,
  OM_CODEC_H266 = OM_MAGIC('VVC1'),
  OM_CODEC_VVC = OM_CODEC_H266,
  OM_CODEC_EVC = OM_MAGIC('EVC1'),
  OM_CODEC_LCEVC = OM_MAGIC('LCVC'),
  OM_CODEC_VP8 = OM_MAGIC('VP08'),
  OM_CODEC_VP9 = OM_MAGIC('VP09'),
  OM_CODEC_AV1 = OM_MAGIC('AV01'),
  OM_CODEC_MPEG4 = OM_MAGIC('MP4V'),
  OM_CODEC_THEORA = OM_MAGIC('theo'),
  OM_CODEC_VC3 = OM_MAGIC('AVdn'),
  OM_CODEC_DNXHD = OM_CODEC_VC3,

  // Audio codecs
  OM_CODEC_PCM_U8 = OM_MAGIC('u08l'),
  OM_CODEC_PCM_S16LE = OM_MAGIC('s16l'),
  OM_CODEC_LPCM = OM_CODEC_PCM_S16LE,
  OM_CODEC_PCM_S32LE = OM_MAGIC('s32l'),
  OM_CODEC_PCM_S16BE = OM_MAGIC('s16b'),
  OM_CODEC_PCM_S32BE = OM_MAGIC('s32b'),
  OM_CODEC_PCM_F32LE = OM_MAGIC('f32l'),
  OM_CODEC_PCM_F64LE = OM_MAGIC('f64l'),
  OM_CODEC_FLAC = OM_MAGIC('fLaC'),
  OM_CODEC_MP2 = OM_MAGIC('.mp2'),
  OM_CODEC_MP3 = OM_MAGIC('.mp3'),
  OM_CODEC_AAC = OM_MAGIC('aac '),
  OM_CODEC_OPUS = OM_MAGIC('Opus'),
  OM_CODEC_VORBIS = OM_MAGIC('VRBS'),
  OM_CODEC_ALAC = OM_MAGIC('alac'),
  OM_CODEC_APE = OM_MAGIC('APE '),
  OM_CODEC_WMA = OM_MAGIC('WMA '),
  OM_CODEC_DTS = OM_MAGIC('DTS '),
  OM_CODEC_AC3 = OM_MAGIC('ac-3'),
  OM_CODEC_EAC3 = OM_MAGIC('ec-3'),

  // Image codecs
  OM_CODEC_JPEG = OM_MAGIC('JPEG'),
  OM_CODEC_JPEGXL = OM_MAGIC('jxl '),
  OM_CODEC_JPEGXR = OM_MAGIC('jxr '),
  OM_CODEC_PNG = OM_MAGIC_RAW(0x89, 'P', 'N', 'G'),
  OM_CODEC_WEBP = OM_MAGIC('WEBP'),
  OM_CODEC_BMP = OM_MAGIC_RAW('B', 'M', 0x00, 0x00),
  OM_CODEC_GIF = OM_MAGIC('GIF8'),
  OM_CODEC_TIFF = OM_MAGIC('II42'),
  OM_CODEC_AVIF = OM_MAGIC('avif'),
  OM_CODEC_HEIC = OM_MAGIC('heic'),
  OM_CODEC_TGA = OM_MAGIC('TGA '),
  OM_CODEC_EXR = OM_MAGIC_RAW(0x76, 0x2F, 0x31, 0x01),
};

OM_ENUM(OMProfile, uint32_t) {
  OM_PROFILE_NONE = 0,

  // H.264
  OM_PROFILE_H264_BASELINE = 66,
  OM_PROFILE_H264_CONSTRAINED_BASELINE = 578,
  OM_PROFILE_H264_MAIN = 77,
  OM_PROFILE_H264_EXTENDED = 88,
  OM_PROFILE_H264_HIGH = 100,
  OM_PROFILE_H264_HIGH_10 = 110,
  OM_PROFILE_H264_HIGH_422 = 122,
  OM_PROFILE_H264_HIGH_444 = 144,
  OM_PROFILE_H264_HIGH_444_PREDICTIVE = 244,

  // H.265
  OM_PROFILE_H265_MAIN = 1,
  OM_PROFILE_H265_MAIN_10 = 2,
  OM_PROFILE_H265_MAIN_STILL_PICTURE = 3,
  OM_PROFILE_H265_REXT = 4,
  OM_PROFILE_H265_MAIN_12 = 5,
  OM_PROFILE_H265_MAIN_4_2_2_10 = 6,
  OM_PROFILE_H265_MAIN_4_2_2_12 = 7,
  OM_PROFILE_H265_MAIN_4_4_4_10 = 8,
  OM_PROFILE_H265_MAIN_4_4_4_12 = 9,
  OM_PROFILE_H265_SCC = 10,

  // H.266
  OM_PROFILE_H266_MAIN_10 = 1,
  OM_PROFILE_H266_MAIN_10_444 = 33,

  // VP9
  OM_PROFILE_VP9_0 = 0, // 8-bit, 4:2:0
  OM_PROFILE_VP9_1 = 1, // 10 or 12-bit, 4:2:0
  OM_PROFILE_VP9_2 = 2, // 8-bit, 4:2:2 or 4:4:4
  OM_PROFILE_VP9_3 = 3, // 10 or 12-bit, 4:2:2 or 4:4:4

  // AV1
  OM_PROFILE_AV1_MAIN = 0,
  OM_PROFILE_AV1_HIGH = 1,
  OM_PROFILE_AV1_PROFESSIONAL = 2,

  // AAC
  OM_PROFILE_AAC_MAIN = 1,
  OM_PROFILE_AAC_LC = 2,
  OM_PROFILE_AAC_SSR = 3,
  OM_PROFILE_AAC_LTP = 4,
  OM_PROFILE_AAC_HE = 5,
  OM_PROFILE_AAC_HE_V2 = 29,
  OM_PROFILE_AAC_LD = 23,
  OM_PROFILE_AAC_ELD = 39,
  OM_PROFILE_AAC_USAC = 42,
  OM_PROFILE_MPEG2_AAC_LOW = 128,
  OM_PROFILE_MPEG2_AAC_HE = 131,
};

#if defined(__cplusplus)
}
#endif
